### ISSUE TITLE
Warm up fails, SymbiYosys says the trace exists when it doesn't

### ISSUE THREAD

**Issue by ZipCPU** [YosysHQ/SymbiYosys#10]
I have a design whose warmup fails.  SymbiYosys declares that the counter example trace is placed into engine_0/trace.vcd.  However, since this is a warmup failure, there is no trace.

Expected behavior: SymbiYosys should say nothing about a trace, or rather say that the trace does not exist because this is a warmup failure.

SymbiYosys directory available upon request.

**Comment by cliffordwolf** [comment]
Fixed in f2697c2.
