### ISSUE TITLE
Unexpected assertion behaviour 

### ISSUE THREAD

**Issue by saw235** [YosysHQ/SymbiYosys#128]
Not sure if this is a bug, but I am getting failed assertion on the assert statement below, even though the counterexample waveform shows that data_wr_strobe is stable across two cycles. Which should make the assertion vacuously True, if I understand it correctly.
![image](https://user-images.githubusercontent.com/10379864/133969540-4bc5f1be-c767-4712-94ec-9249970a8c16.png)
![image](https://user-images.githubusercontent.com/10379864/133969462-21d35f2b-5eed-4c39-a9bc-eeee7f98d653.png)

**Comment by piegamesde** [comment]
To help finding out more about the issue, please try to minimize the code example: strip away piece after piece while checking that the assertion fails although it shouldn't until you cannot remove any more without making it work again.

**Comment by saw235** [comment]
Hi even after I stripped down to its bare minimum, it is unclear what is happening. My only guess is that the $stable() does not work like I understand it to be, or that the initial value starts off as 'X' and changes to 0 which makes the assertion fails. 
In the second case, I have no clue how I can get the tool to ignore time 0.

![image](https://user-images.githubusercontent.com/10379864/134058144-c448763e-7539-4862-af5a-3a01a6406876.png)
![image](https://user-images.githubusercontent.com/10379864/134058186-1df33627-2894-45a9-b026-ec78b4996eb2.png)

**Comment by EngRaff92** [comment]
Your clk starts as one meaning there is an active edge there, make an initial where you set the clk to 0, then in clk gen do always #<yourtime> clk = ~clk. To ignore time zero let the assert not be triggered by simply avoid using an evaluation point at that time. Properties has disable iff to let it be settled under reset

**Comment by saw235** [comment]
@EngRaff92 Thanks. I figured out what's wrong and managed to come up with a solution to ignore the first cycles by referencing the ibex repository.
