### ISSUE TITLE
super_prove binary for Ubuntu 16.04

### ISSUE THREAD

**Issue by vineeshvs** [YosysHQ/SymbiYosys#13]
Couldn't find a super_prove binary for Ubuntu 16.04 in [https://downloads.bvsrc.org/super_prove/](https://downloads.bvsrc.org/super_prove/). Please add if possible.

**Comment by ZipCPU** [comment]
Did you struggle to build super_prove at all?

Dan

**Comment by cliffordwolf** [comment]
We don't maintain super_prove. Here is the github repo for it: https://github.com/berkeley-abc/super_prove
