### ISSUE TITLE
Suggested update to the main README file

### ISSUE THREAD

**Issue by ZipCPU** [YosysHQ/SymbiYosys#16]
Several individuals have struggled with the initial concepts of Formal Verification.  A classic example would be this [issue](https://github.com/YosysHQ/SymbiYosys/issues/12), which I've [written about extensively](http://zipcpu.com/blog/2018/03/10/induction-exercise.html) at [ZipCPU.com](http://zipcpu.com).  I've now written [many articles on the topic](http://zipcpu.com/formal/formal.html) and posted them to [ZipCPU.com](http://zipcpu.com).  

Therefore, I'm recommending the following patch to the SymbiYosys readme file, to reference these articles.

Dan

```
diff --git a/README.md b/README.md
index 7363d8e..e996989 100644
--- a/README.md
+++ b/README.md
@@ -1,5 +1,10 @@
 
-SymbiYosys (sby) is a front-end driver program for Yosys-based formal
-hardware verification flows. See http://symbiyosys.readthedocs.io/ for
-documentation.
+SymbiYosys (sby) is a front-end driver program for
+[Yosys](http://www.clifford.at/yosys)-based formal hardware verification flows. See [http://symbiyosys.readthedocs.io/](http://symbiyosys.readthedocs.io/) for
+documentation on how to use SymbiYosys.
+
+Many example designs using SymbiYosys have been published on the
+[ZipCPU blog](http://zipcpu.com).  Please consider browsing the
+[formal verification page](http://zipcpu.com/formal/formal.html)
+of the [ZipCPU blog](http://zipcpu.com) for examples and commentary.

```

**Comment by cliffordwolf** [comment]
Applied in 896f181.
