### ISSUE TITLE
Unexpected behavior with tasks

### ISSUE THREAD

**Issue by ZipCPU** [YosysHQ/SymbiYosys#17]
Problem: If an .sby file references an undefined task, the commands associated with that task are executed by default

Example SymbiYosys script:

[tasks]
A
[script]
A: do_something_one
B: do_something_two

Expected behavior: Undefined task references should create an error, or at least not be executed.

Example file attached.
[broken-ex.txt](https://github.com/YosysHQ/SymbiYosys/files/2358494/broken-ex.txt)
In this example file, the chparam command line for the undefined task, ck3_r2, is executed.  While not defining the task in the script, I wasn't expecting yosys to implement the commands within it.

Dan

**Comment by cliffordwolf** [comment]
This should be fixed now in current git HEAD.
