### ISSUE TITLE
Use more Python standard libraries

### ISSUE THREAD

**Issue by wifasoi** [YosysHQ/SymbiYosys#25]
We can harness the power of [ArgParse](https://docs.python.org/3.7/library/argparse.html) (for parsing the arguments) and [ConfigParser](https://docs.python.org/3/library/configparser.html#supported-ini-file-structure) (for the sby file).

The benefit of argparse are:
* included in python standard library
* easy to add menu entry
* no more if ladders :D
* parameter checking
* semi-automatic help
* many more (but not relevant right for this issue)

Didn't use ConfigParse much, but I can look if it can replace the parser class with all the feature intact.

If you dean this change worthy, I can work (albeit slowly) on it.

**Comment by wifasoi** [comment]
Ok, I evaluated the sue of ConfigParse for the sby file; Is not feasible with the current sby file structure (ConfigParse need every entry written in a key-value fashion). Unless we are willing to change the file structure (I doubt that anyone wold want to do that), ignore the second part of the issue :)

**Comment by rhthomas** [comment]
I thought the same after looking into the code a bit. @wifasoi not sure if you started working on this or not, but I've started to give it a go on my [fork](https://github.com/rhthomas/SymbiYosys/tree/argparse) if you're interested?

**Comment by wifasoi** [comment]
I'm not working on this.
I'm not the developer.. but i can always say thank you :)

**Comment by cliffordwolf** [comment]
See #52.
