### ISSUE TITLE
installing error SymbiYosys  

### ISSUE THREAD

**Issue by GoldenHamed** [YosysHQ/SymbiYosys#26]
hello,
Getting a following error while installing SymbiYosys:

![screenshot from 2019-01-20 23-04-38](https://user-images.githubusercontent.com/46302702/51444171-60f39c80-1d09-11e9-995e-f14f277a7c5d.png)

please help me.

**Comment by cliffordwolf** [comment]
Good News: That's not an error. You just successfully installed SymbiYosys.
