### ISSUE TITLE
SymbiYosys crashes

### ISSUE THREAD

**Issue by ZipCPU** [YosysHQ/SymbiYosys#29]
See the attached SBY-created directory.

[wbxbar2.zip](https://github.com/YosysHQ/SymbiYosys/files/2948411/wbxbar2.zip)

SymbiYosys is crashing with an incomprehensible error.  Not sure where to go with finding or fixing it.  I'm expecting errors in the code in question, just not the error messages given.

Verific fails on this with a trace that doesn't make sense either, but I'll make that a separate bug, if I can play the two against each other.  That is, the Verific version produces a trace (albeit one that doesn't appear to match the logic).

**Comment by cliffordwolf** [comment]
Fixed in https://github.com/YosysHQ/yosys/commit/94f995ee3784e1a94a484fd399be2be4793d4e41
