### ISSUE TITLE
Some engines cause SymbiYosys to crash

### ISSUE THREAD

**Issue by ZipCPU** [YosysHQ/SymbiYosys#3]
See the example at http://zipcpu.com/tmp/ybug9.tgz.

The example consists of a proof that two LFSRs, a Galois and a Fibonacci one, are equivalent.

smtbmc comes up with an inconclusive answer, abc pdr passes.  These are understandable results.

However, aig avy and aig suprove both result in crashes.

Dan

**Comment by cliffordwolf** [comment]
It should be `aiger avy` and `aiger suprove`, not `aig avy` and `aig suprove`. (Unfortunately all error handling in sby is currently done with python asserts. I realize that this is not optimal.)

I've now also added support for comments at the end of lines in 221c8d2. Until now only comments on their own lines where supported.
