### ISSUE TITLE
disable iff is sensitive beyond the sensitivity of the assertion

### ISSUE THREAD

**Issue by ZipCPU** [YosysHQ/SymbiYosys#31]
When using disable iff, SymbiYosys is sensitive to the clock after the assertion/assumption is to take place.  Consider, for example, the following MCVE:

[mcve.zip](https://github.com/YosysHQ/SymbiYosys/files/2952498/mcve.zip)

In it, there's a two clock assertion that should take place on clocks 0 and 1.  This assertion is disabled by the reset signal.  Hence, it should only be checked if the reset signal is true on clocks 0 and 1.  However, the reset signal is low on clocks 0 and 1, only to be raised on clock 2.  This invalidates the assertion when it should not.

So the sequence is: Good ##1 should fail ##1 reset, and the result is that it does not fail.

The cover statement in the attached MCVE shows that the assertion should have failed.

Dan

**Comment by cliffordwolf** [comment]
Seems like the current behavior is std compliant: https://www.edaplayground.com/x/5Jij  
(or at least matches Riviera Pro :)
