### ISSUE TITLE
boolector licensing?

### ISSUE THREAD

**Issue by mithro** [YosysHQ/SymbiYosys#41]
From https://symbiyosys.readthedocs.io/en/latest/quickstart.html#selecting-the-right-engine there is the following statement;

> smtbmc boolector uses boolector as SMT solver. Note that boolector is only free-to-use for noncommercial purposes. Use smtbmc z3 to use the permissively licensed solver Z3, or use smtbmc yices to use the copyleft licensed solver Yices 2 intead. Yices 2 is the default solver when no argument is used with smtbmc.

However it looks like boolector is [released under a MIT license](https://github.com/boolector/boolector#contributing)? boolector supports the permissively licensed CaDiCaL, PicoSAT and MiniSAT for SAT solving.

The only engine which seems to be under a non-commercial only license seems to be Lingeling. Is the boolector backend only useful when used with Lingeling?

**Comment by cliffordwolf** [comment]
It makes most sense with Lingeling. Lingeling is certainly faster than any of the other back-ends.
