### ISSUE TITLE
SymbiYosys crashes while generating a cover trace

### ISSUE THREAD

**Issue by ZipCPU** [YosysHQ/SymbiYosys#45]
I'm not quite sure what's causing this, but my best guess is that a recent yosys upgrade, perhaps to create better names, is now causing SymbiYosys to crash when it tries to generate VCD files.

See the attached SymbiYosys directory, and logfile within it

[wbxbar_cvr1x3_buf.zip](https://github.com/YosysHQ/SymbiYosys/files/3149817/wbxbar_cvr1x3_buf.zip)

**Comment by cliffordwolf** [comment]
Thanks for the test case. That seems to be a bug in `write_smt2`. I'll have a look a bit later today.

**Comment by cliffordwolf** [comment]
Fixed in https://github.com/YosysHQ/yosys/commit/a76189e7adb88a81b8c1a8910524323fe93a421c.
