### ISSUE TITLE
yosys treats default keyword in a case expression as an identifier

### ISSUE THREAD

**Issue by jfierro** [YosysHQ/SymbiYosys#53]
This comes from ZipCPU's "Building hello world, using a serial port transmitter" tutorial, which can be found [here](http://zipcpu.com/tutorial/). I have attached the zip file containing the txuart.v and txuart.sby files used in the tutorial for convenience. I can reproduce the issue with these as follows:

    ex-05-hello$ sby -f txuart.sby
    SBY 14:35:52 [txuart] Removing direcory 'txuart'.
    SBY 14:35:52 [txuart] Copy 'txuart.v' to 'txuart/src/txuart.v'.
    SBY 14:35:52 [txuart] engine_0: smtbmc yices
    SBY 14:35:52 [txuart] base: starting process "cd txuart/src; yosys -ql ../model/design.log ../model/design.ys"
    SBY 14:35:52 [txuart] base: txuart.v:235: ERROR: Identifier `\default' is implicitly declared and `default_nettype is set to none.
    SBY 14:35:52 [txuart] base: finished (returncode=1)
    SBY 14:35:52 [txuart] base: job failed. ERROR.
    SBY 14:35:52 [txuart] summary: Elapsed clock time [H:MM:SS (secs)]: 0:00:00 (0)
    SBY 14:35:52 [txuart] summary: Elapsed process time [H:MM:SS (secs)]: 0:00:00 (0)
    SBY 14:35:52 [txuart] DONE (ERROR, rc=16)
    ex-05-hello$ yosys -V
    Yosys 0.8+572 (git sha1 c4c39e98, clang 7.0.0-3 -fPIC -Os)

As you can see from the attached txuart.v file, line 235 is a default case item in a case expression.

[ex-04-reqwalker.zip](https://github.com/YosysHQ/SymbiYosys/files/3347234/ex-04-reqwalker.zip)

**Comment by cliffordwolf** [comment]
Note: Actual zip file with the file in question: http://zipcpu.com/tutorial/ex-05-hello.zip
