### ISSUE TITLE
Cannot run demo example from docs - ERROR: No such command: memory_nordff

### ISSUE THREAD

**Issue by rick-heig** [YosysHQ/SymbiYosys#8]
When running the example from : 
[First step: A simple BMC example](http://symbiyosys.readthedocs.io/en/latest/quickstart.html#first-step-a-simple-bmc-example)

I get an error message from SBY

$ sby demo.sby 
SBY 12:32:24 [demo] Copy 'demo.v' to 'demo/src/demo.v'.
SBY 12:32:24 [demo] engine_0: smtbmc
SBY 12:32:24 [demo] base: starting process "cd demo/src; yosys -ql ../model/design.log ../model/design.ys"
SBY 12:32:24 [demo] base: ERROR: No such command: memory_nordff (type 'help' for a command overview)
SBY 12:32:24 [demo] base: finished (returncode=1)
SBY 12:32:24 [demo] base: job failed. ERROR.
SBY 12:32:24 [demo] summary: Elapsed clock time [H:MM:SS (secs)]: 0:00:00 (0)
SBY 12:32:24 [demo] summary: Elapsed process time [H:MM:SS (secs)]: 0:00:00 (0)
SBY 12:32:24 [demo] DONE (ERROR, rc=16)

I have Yosys, SymbiYosys and Yices 2 installed, I tried changing the solver, the error remains the same.
Do you have any insight ? (Running Ubuntu 16.04, followed the installation instructions from the SymbiYosys docs).

Thank you.

**Comment by cliffordwolf** [comment]
You are using an old version of Yosys. Follow the install instructions at http://symbiyosys.readthedocs.io/en/latest/quickstart.html#installing and install Yosy git head.
