### ISSUE TITLE
"Removing direcory"

### ISSUE THREAD

**Issue by kentindell** [YosysHQ/SymbiYosys#89]
Can the typo be fixed in the next release? :)

**Comment by nakengelhardt** [comment]
This was fixed in #70 back in January, just pull latest master! (I don't think SymbiYosys itself has proper release versions? Are you getting it from somewhere else, e.g. included with SEDA Suite?)

**Comment by kentindell** [comment]
It seems I have been trapped in a maze of twisty VMs, all alike, and the *only* one that is older than January is the one I submitted this from.
